### ISSUE TITLE
Dgs-exedit sometimes don't display it's content until you click them

### ISSUE THREAD

**Issue by ERAGON007** [thisdp/dgs#118] opened 2023-02-10 17:52 UTC

**Comment by thisdp** [comment] 2023-02-11 09:28
because of the optimization, DGS edit only renders when visual property changes. There may be some condition missing.

**Comment by ERAGON007** [comment] 2023-02-13 21:18
Alright, didn't know about that, feel free to close this issue when you want. or it can be open until conditions are added

**Comment by xLive** [comment] 2023-04-26 13:17
How to reproduce this?

**Comment by ERAGON007** [comment] 2023-04-26 14:36
> How to reproduce this?

I don't remember rn but you could reproduce it by setting the parent element visible to false first and try to set it to true after creating edit

**Comment by xLive** [comment] 2023-04-28 00:25
Just for the record, after a little investigation, I found that the cause of this issue is minimizing the game while the editbox/memo is invisible.
When you minimize the game, rendertargets are cleared, but DGS restores them when you restore the game. 
https://github.com/thisdp/dgs/blob/e1ba5c3df2e5af77c35b5989ac69a667b0c5b271/client.lua#L136-L138 However, since invisible elements do not render, they miss the `RTRestoreNeed` check, which leads to rendertargets not being restored, causing this issue.

I will investigate more soon when I have some free time, but if someone wants to fix it, feel free to do so

**Comment by xLive** [comment] 2023-07-06 21:50
This bug has been resolved in previous commits.

**Closed by xLive** 2023-07-06 21:50 UTC
Labels: bug
